### ISSUE TITLE
Outdated packages

### ISSUE THREAD

**Issue by SamambaMan** [bsvetchine/django-payzen#3]
Hi all

When importing django urls.py and adding it to my urls.py I receive:
Unhandled exception in thread started by <function wrapper at 0x7f002541bb90>
Traceback (most recent call last):
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/felipe/AloWiFi/VersionControl/Backend/mapptvadmin/mapptvadmin/urls.py", line 19, in <module>
    url(r'^payment/', include("django_payzen.urls")),
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django_payzen/urls.py", line 1, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name patterns

This is due the removal of the django patterns was removed on django 1.10 and deprecated in django 1.8.

Are you planing to update this package?

Thanks in advance!

**Comment by SamambaMan** [comment]
Updated the urls.py as:
from django.conf.urls import  url

from . import views

urlpatterns = [
    url(r"^response/$", views.ResponseView.as_view(),
        name="django_payzen_response"),
]

And it worked as it should, but again when generating the payzenform:

Internal Server Error: /pagamento/
Traceback (most recent call last):
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/felipe/AloWiFi/VersionControl/Backend/mapptvadmin/mapptvadmin/videomanager/views.py", line 164, in Pagamento
    return render(request, template, {'payment_request': payment_request})
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/template/loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/template/loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/template/utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/template/utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 48, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 113, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 126, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/felipe/.virtualenvs/mapptv/local/lib/python2.7/site-packages/django_payzen/templatetags/payzen_extras.py", line 6, in <module>
    register = template.base.Library()
AttributeError: 'module' object has no attribute 'Library'


Updated the payzsen_extras.py as: 
register = template.base.Library()
to:
register = template.Library()

And it worked as it should.
